name: 🧲 Activador Imán Bot Core

on:
  workflow_dispatch:
  push:
    paths:
      - '**.js'
      - '.github/workflows/imantador.yml'

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Clonar el repositorio
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🧲 Ejecutar el bot
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: tiktok-iman-bot-core
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node main.js
